JuliaIO/EzXML.jl

test/runtests.jl

@clarkevans I'd like to include your case in unit tests if you don't mind.
xref: #8

add a test for #8

---

docs/src/manual.md

Two small misspellings were corrected.

Minor spelling corrections

---

example/graphml.jl

Deprecated function

---

src/node.jl
src/streamreader.jl
src/xpath.jl
test/runtests.jl

Fix memory management of nodes

---

README.md
src/document.jl
src/node.jl
test/runtests.jl

add document and node properties

---

README.md
docs/src/index.md
docs/src/manual.md
docs/src/references.md
example/listlinks.jl
example/primates.jl
src/EzXML.jl
src/xpath.jl
test/runtests.jl

Change the argument order of find* functions

---

src/node.jl
test/runtests.jl

add tree traversal properties

---

src/xpath.jl
test/runtests.jl

make findfirst and findlast return nothing

---

src/EzXML.jl
src/streamreader.jl
test/runtests.jl

add stream reader properties

---

.travis.yml
REQUIRE
appveyor.yml
src/node.jl

Summary of changes:
* Use `something` instead of `coalesce`. Fixes #66.
* Add 0.7-alpha testing to the CI setup.

Updates for latest Julia 0.7

---

src/node.jl
src/streamreader.jl

is this what you want for #78? 
``` julia
using EzXML
docstr = """
<?xml version="1.0" encoding="UTF-8"?>
<root>
<foo>ok</foo>
</root>
"""
doc = parsexml(docstr)
show(doc)
> EzXML.Document(EzXML.Node(<DOCUMENT_NODE@0x000000001014d320>))
import EzXML.Node
show(doc)
> EzXML.Document(Node(<DOCUMENT_NODE@0x000000001014d320>))
```

Printing imported names

---

.travis.yml
appveyor.yml
src/node.jl
src/streamreader.jl
src/xpath.jl
test/runtests.jl

Note I originally started this work accidentally on an old branch so I came up with a slightly different iterate functions than you did. I left mine in as I think they are easier to read. However, I understand that is subjective so let me know if you'd prefer the versions you had.

Support Julia 1.0

---

src/streamreader.jl

I think no reason to keep it mutable.

make AttributeReader immutable

---

src/node.jl
test/runtests.jl

show the name of elements and attributes

---

src/document.jl

add missing show_warnings to parsehtml

---

src/xpath.jl
test/runtests.jl

, which would be helpful in cases like #127.

warn empty prefix for namespace

---

docs/src/manual.md

Just submitting a spelling error in the manual. Hope I'm following correct procedure.

correct spelling error

---

src/error.jl

I was confused to get this message an then have nothing shown,

Throwing, not showing, only first error.

---

.github/workflows/CI.yml
Project.toml
test/runtests.jl

- Add Aqua
- Fix compat entries in Project.toml

prep for 1.2.0

---

.github/workflows/CI.yml
.github/workflows/Downstream.yml
Project.toml
README.md
test/Project.toml
test/runtests.jl

Fixes #152
The most recent version of XML2_jll is breaking some of the tests. I marked those tests as broken.

Update CI and fix readme links

---

.github/workflows/Downstream.yml

XLSX.jl no longer depends on EzXML.jl

Remove XLSX.jl from Downstream.yml

---

Project.toml

This version includes #206 which fixes #200

Bump version to 1.2.1
